DROP TABLE IF EXISTS instrument;
CREATE TABLE instrument (
	id INTEGER PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	category VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS musician;
CREATE TABLE musician (
	id INTEGER PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	DoB INTEGER NOT NULL
);

DROP TABLE IF EXISTS band;
CREATE TABLE band (
	id INTEGER PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	genre VARCHAR(100) NOT NULL,
	year INTEGER NOT NULL
);

DROP TABLE IF EXISTS album;
CREATE TABLE album (
	id INTEGER PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	released INTEGER NOT NULL
);

DROP TABLE IF EXISTS website;
CREATE TABLE website (
	id INTEGER PRIMARY KEY,
	url VARCHAR(100) NOT NULL,
	visits_per_month INTEGER NOT NULL,
	online_store BOOLEAN NOT NULL
);


